### ISSUE TITLE
Style Variations

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/fork#2]
### Style 1 (default)

Color | hex value
--- | --- |
|background| `#FFFFFF` |
|foreground | `#202020` |
|background-alt |`#EDEAE4` |
|background-inv |`#1A1919` |
|foreground-alt | `#FBFBFB` |
|accent | `#435DEB` |

### Style 2 - Spice cream

Color | hex value
--- | --- |
|background| `#EDEAE4` |
|foreground | `#202020` |
|background-alt |`rgba(255, 255, 255, 0.5)` |
|background-inv |`#272727` |
|foreground-alt | `#FFFFFF` |
|accent | `#EB7F42` |

### Style 3 - Violet Dense

Color | hex value
--- | --- |
|background| `#292928` |
|foreground | `#FFFFFF` |
|background-alt |`rgba(255, 255, 255, 0.5)` |
|background-inv |`#272727` |
|foreground-alt | `#FBFBFB` |
|accent | `#8E68A0` |

### Style 4 - Light organic

Color | hex value
--- | --- |
|background| `#FFFFFF` |
|foreground | `#202020` |
|background-alt |`rgba(0, 0, 0, 0.3)`  |
|background-inv |`#323F30` |
|foreground-alt | `#FDFDFD` |
|accent | `#628E5B` |

### Style 5 - Electro blue

Color | hex value
--- | --- |
|background| `#2A3148` |
|foreground | `#FFFFFF` |
|background-alt |`rgba(255, 255, 255, 0.5)` |
|background-inv |`rgba(0, 0, 0, 0.3)` |
|foreground-alt | `#FBFBFB` |
|accent | `#4889A5` |

### Style 6 -Paper purple

Color | hex value
--- | --- |
|background| `#EEEAE2` |
|foreground | `#202020` |
|background-alt |`rgba(0, 0, 0, 0.5)` |
|background-inv |`#493A50` |
|foreground-alt | `#ffffff` |
|accent | `#8E68A0` |

**Comment by abaicus** [comment]
Closing this as style variations were added 🎉
