### ISSUE TITLE
Site title style

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/fork#4]
@abaicus whenever you have the chance, where is the site title styling defined? I did not see it in the theme.json.
I'd like to make it smaller, and in different weight. Do you have any suggestion on how to tweak the style?

https://handsomepoint.s2-tastewp.com/

Thanks in advance!

**Comment by abaicus** [comment]
@JohnPixle The site title style can't be managed from the theme.json, unfortunately. We have an SCSS file where we can add code.

https://github.com/codeinwp/fork/blob/97b48f9c2790fbf182b2a6afcc4d82616561cc7a/assets/css/src/blocks/_site-title.scss

I can also add the changes myself if you let me know the exact values 🚀
